version: '3.9'

services:
  ksnetwork:
    container_name: ksnetwork
    image: haeramkeem/ksnetwork
    ports:
      - 5000:5000
    restart: always
    environment:
      - "host=${DB_HOST}"
      - "dbname=${DB_NAME}"
      - "user=${DB_USERNAME}"
      - "password=${DB_PASSWORD}"
      - "port=${DB_PORT}"
